select *
from harmonized.dim_passenger
at (timestamp=> dateadd(minute, -5, current_timestamp()));


CREATE OR REPLACE TABLE HARMONIZED.DIM_PASSENGER_CLONE
CLONE HARMONIZED.DIM_PASSENGER
AT (TIMESTAMP => DATEADD(MINUTE, -10, CURRENT_TIMESTAMP()));



CREATE SECURE VIEW ANALYTICS.V_FLIGHT_SUMMARY_SECURE AS
SELECT *
FROM ANALYTICS.FLIGHT_SUMMARY;

ALTER TABLE ANALYTICS.FLIGHT_SUMMARY
ADD ROW ACCESS_POLICY country_rls
ON (country_name);